grafana:
    password: ENC[AES256_GCM,data:ZAj5a34wF0cswkxpLkpbNB7tkD4ibyOfgFn5Yv363RC+4kBFx3n0kGyy1w==,iv:iUEHod9pHBuj/jsbp0aEpK/5XFyU3wePsaCrFfYnBWg=,tag:96UCGArvqmqyt9Z+SWxiWw==,type:str]
porkbun:
    api_key: ENC[AES256_GCM,data:tsh0m9IayHXyIAX91JlZwOUyqrM5o0WXSIsUnvfmkK8noqFbOIxtXelhawkhT6E5oXmohtknde3jKmR5ET7hgw6g0Os=,iv:5Vsr0U2QNkhB+uV1vvCtm7DlZAAZ8MwjA3a0GUaAU4g=,tag:QEMuayuflIeLYVv3OQPk2w==,type:str]
    secret_key: ENC[AES256_GCM,data:3wqDp9W4UZiVxlMmqBUAn1HsF+L6ZDU4O06h7gj9tTPylfQi0/cqd2bdCivCr3RnVNOdKq+l3+3o8Ifl1MWFjbVSDvQ=,iv:hnQPHOYi/rx15kEGyTH27lEAsnxUKWZUZWD6Qxvl+uw=,tag:eIpU5Hb7wD11nT+ft04i/Q==,type:str]
    domain: ENC[AES256_GCM,data:FRqSGcTShGWx,iv:8m2qlLE5CwwPkO6Rxzy3NK4Ef0SP3skdUvylU5D1M8A=,tag:a/f/kAQEzOHxpITkym//VA==,type:str]
certmanager:
    email: ENC[AES256_GCM,data:e5B2kdNeLj7HeC0l1RI5D1VGyNPO,iv:wR/5dBFhW1H4YM99wwQVv1Hym69pEJRN+NZmRipStc0=,tag:mVkHOgEa3IRYow1NoimykA==,type:str]
slack:
    api_url: ENC[AES256_GCM,data:WsKExv6YTP+Mg1qDC0uxihqYk36QQd9oFpCDXAolO/tEoEGBjzELg4OouJk+PVLCk97yllSnhB1iY7AVIzhaYm2xdc10ysaAwCc0/U1Faym1,iv:yxt5w2WVMLyRWRPxYW3Clv/dNcInfwH2o3gGEjk5xkI=,tag:gIW/t8MmS3n8+7P2FKnsKQ==,type:str]
civo:
    token: ENC[AES256_GCM,data:q8kjIKF39zmi1QCBQBfdQ+c73AphoBSoDC3hqTkhAYK3P2q26c1RY+8az59sHK/AZv8=,iv:1KUCWAr3Aze4bZQilQNxsg66gSE0INtdgSM1qILdjpI=,tag:91tSPXxVtWH1vzmcu/X4QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t2al77nhtazslzknxrxffdjf27fqyehejna7sxt2e97fwwx5pls5clc4s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOG9DZWNSRG9YeEdoakth
            SUxZL3JMNVZsSmFUd2JJQUcyWlhZZDlLdFdnCjU2QmhXcjdiWVlWcS8zcmJMT3d6
            NGlBWWk4WGhsdUZueTdPamhjazA2U3cKLS0tIGdsR1VURGJlejhoYWlqeXlTQkI4
            ZTN3bUxzLzlvaGxLVWpKSE05MjlVY1UKKhTGn2DKF2zFn8/ywHIO0PrH+i4ihbmm
            OkYGdbNhM2yvv4oDxXJr6sD0QQGuT24CAeHHRL4tfdZXcCbVNA7CNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T22:10:27Z"
    mac: ENC[AES256_GCM,data:MxBvWRZr/+o5uWsKYg4mZiJ3LCsNxmXFFf2X7FIT65YAcJqr+rjKI7itqu+iC34sOkdtru3nQV7VAlJ2fZKZ3Iiy/DOjnqNIgoBQMZp4OxYHuBCqcjgnQf/vzlqdFT5uH7eAGibGxadLJnXFYp+41okCrRpOGLeCU/SsD/x6Iko=,iv:G2IJ1ho4A/XlF3hM8AVc5qL1/a/7NRIyI5QZO+vGytI=,tag:NjECAXmNS/C/AYnfVBfxMg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
