grafana:
    password: ENC[AES256_GCM,data:YDRTPyZ9Z+ukcWJR4q5i4j5e8gYcmiMpcKFau931mrAzD871OI9U2z19NQ==,iv:ck6cfmEDr6H/ib0+vY7z5wn2PyiGMTZf+bgMN5XxuEE=,tag:Qpjq04P+DLif+foXhpvUug==,type:str]
porkbun:
    api_key: ENC[AES256_GCM,data:e/hxkOUx5kWIsikKTkaQeh2ITKt4JGaG5zihegBjDrzSJ3hS5bxMMUKKb2TltVIZem8s2ps8k7mCTzugd5HX455xJN4=,iv:2JSlsgWbiah33PkKkiJnol8mygpK6j89Z+e1fK91/PA=,tag:H/Bb44H9bXG1SszT8SMj5w==,type:str]
    secret_key: ENC[AES256_GCM,data:ni3CFT26H9ra3Otezn/I+LWgqdfvlEHGwL9+4wZN5Za3utPUHmui70jXzte09Ln6Ykcg7BhAnYAjYxhFkIEWu5yex48=,iv:+KKyw9SQ9TmPLU58z2EYcK12B/vOpagVF+euTeHksX4=,tag:wg9DTFSG2kjueM2TcQlh4w==,type:str]
    domain: ENC[AES256_GCM,data:kfZOlPEh6N4N,iv:FNSWWhN12r+XY/bpIzDWst8xSj28aPCq0KItcY5yw7U=,tag:HcLk2TSZKMXAnjfWph8MIw==,type:str]
certmanager:
    email: ENC[AES256_GCM,data:YGabdCseETNR/j6R9XMGJi8/60rZ,iv:dHmFHQsfi9AZ8Uyjp4zZBhwRCpJ3bQwGRkm9MES20TA=,tag:ASgyFpUIRGYF0whqKB8Bbw==,type:str]
slack:
    api_url: ENC[AES256_GCM,data:c/kCg7VNwURQDHwzDbySGwXG+3Twz/D9ChmS8yiNRK3xZc0dHnU6b9s6TjQu6yeVX2AJQ0brlqkAOkXZ+Z+9H36tM4LInp4pnmr/JEhQm0c0,iv:qi34Y6OJCRbrT2po+mljyp3bqZLL7m9Y9nGdooyB17Q=,tag:UeNdqDg4KjjAYspG1P0EXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19t2al77nhtazslzknxrxffdjf27fqyehejna7sxt2e97fwwx5pls5clc4s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY2cvcEFsR2tvN1lydkc0
            eUhnYXFBR09OemFWN1hwc0grWE95Qmp4NlhNClc0TFZEQW96aWV4bm9qK2lBT2NG
            V1ZSd3NMajVCWjg2UWpuVkpOMGVmN28KLS0tIGVoYVprU2E2Y3FxL3hxRHk0OFJK
            dlhZbjM1eHd6b1RWUVp6VHlJTjFDMGcKeouTOz27Z0NAv9Z8AvZ/jTyS6Rlj+CA9
            Dk1bXVLseZLYpeK5Yc38YfuD9p25X6hCemKhm9rbrAAgdwZhS+67Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T19:48:50Z"
    mac: ENC[AES256_GCM,data:AC2fWMecgTIYDj6EAKgMluTJQsPw7Sn6+v5bBrFjamZ/4yWLXKGr7HfRGdiwF4WXhxUXaD0VThmn/uiSeFY/Ki5B/7/UDoN/mDlmKLMAq9C37XH18jOeYt7QQwbXcMUUNoldTYnJ9vZsnWTYuR6zWj1QM8KTBp5jS0qAS21UYtM=,iv:LreUvnKrwTDtTgwx9O723XQddEWwh1pd9MEPQ6oZbP0=,tag:nw1Lo3chUFPnM1kqOb/Yfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
